"""
Auto-fix generation engine responsible for producing executable
SQL repair suggestions based on deterministic validation warnings.

This utility converts validation issues into actionable SQL fixes
that can be applied manually or integrated into future automated
schema repair workflows.

Currently Supported Auto-Fixes:
- missing foreign key indexes
- missing created_at timestamps
- missing updated_at timestamps

The generated fixes are advisory and are returned as part of
the final schema response.

Used by:
- schema_service
- validation pipeline
- schema repair workflows
"""

from models.schema_models import (
    SchemaResponse,
    AutoFix
)


def generate_auto_fixes(
    schema: SchemaResponse,
    warnings
):
    """
    Generate SQL repair suggestions from validation warnings.

    This method analyzes deterministic validation warnings and
    generates executable SQL statements that resolve detected issues.

    Supported Fix Categories:
        - foreign key index creation
        - missing created_at column addition
        - missing updated_at column addition

    Args:
        schema:
            Structured schema response generated by the
            schema generation pipeline.

        warnings:
            List of deterministic validation warnings generated
            during schema validation.

    Returns:
        list[AutoFix]:
            List of generated SQL repair suggestions.

    Used by:
        - generate_schema_service()

    Notes:
        - Auto-fixes are generated only for supported validators.
        - Generated SQL is advisory and should be reviewed
          before production execution.
        - Current implementation focuses on lightweight
          deterministic repairs.
        - Future versions may support:
            - automated migration generation
            - index optimization fixes
            - relationship repair suggestions
            - normalization improvements
    """

    fixes = []

    for warning in warnings:

        validator = warning.validator

        # ========================================================
        # FOREIGN KEY INDEX AUTO-FIX
        # --------------------------------------------------------
        # Generate CREATE INDEX statements for foreign key
        # columns missing indexes.
        # ========================================================

        if validator == "foreign_key_validator":

            issue = warning.issue

            try:

                # Example issue format:
                # "orders.user_id missing index"

                parts = issue.split(".")

                table_name = parts[0]

                fk_column = (
                    parts[1]
                    .replace(" missing index", "")
                )

                fixes.append(
                    AutoFix(
                        issue=issue,

                        fix_sql=(
                            f"CREATE INDEX "
                            f"idx_{table_name}_{fk_column} "
                            f"ON {table_name}({fk_column});"
                        )
                    )
                )

            # Prevent pipeline failure due to malformed warning format
            except Exception:
                pass

        # ========================================================
        # TIMESTAMP FIELD AUTO-FIXES
        # --------------------------------------------------------
        # Generate ALTER TABLE statements for missing
        # audit timestamp fields.
        # ========================================================

        elif validator == "timestamp_validator":

            issue = warning.issue

            # ----------------------------------------------------
            # created_at Column Fix
            # ----------------------------------------------------

            if "created_at" in issue:

                table_name = issue.split()[0]

                fixes.append(
                    AutoFix(
                        issue=issue,

                        fix_sql=(
                            f"ALTER TABLE {table_name} "
                            f"ADD COLUMN created_at "
                            f"TIMESTAMP WITH TIME ZONE "
                            f"DEFAULT CURRENT_TIMESTAMP;"
                        )
                    )
                )

            # ----------------------------------------------------
            # updated_at Column Fix
            # ----------------------------------------------------

            elif "updated_at" in issue:

                table_name = issue.split()[0]

                fixes.append(
                    AutoFix(
                        issue=issue,

                        fix_sql=(
                            f"ALTER TABLE {table_name} "
                            f"ADD COLUMN updated_at "
                            f"TIMESTAMP WITH TIME ZONE "
                            f"DEFAULT CURRENT_TIMESTAMP;"
                        )
                    )
                )

    # Return all generated SQL repair suggestions
    return fixes