"""
Centralized validator execution pipeline responsible for orchestrating
all deterministic schema validation modules.

This utility acts as the aggregation layer for rule-based validators
used throughout the schema quality assurance workflow.

The validator pipeline executes multiple specialized validators:
- duplicate index detection
- foreign key index validation
- timestamp validation
- enum modeling analysis
- composite index recommendations

Each validator returns structured `DeterministicWarning` objects
that are aggregated into a unified validation result set.

Used by:
- schema_service
- validation pipeline
- auto-fix engine
"""

from utils.validators.duplicate_index_validator import (
    validate_duplicate_indexes
)

from utils.validators.foreign_key_validator import (
    validate_foreign_key_indexes
)

from utils.validators.timestamp_validator import (
    validate_timestamps
)

from utils.validators.enum_validator import (
    validate_enum_modeling
)

from utils.validators.composite_index_validator import (
    validate_composite_indexes
)


def run_validators(schema):
    """
    Execute all deterministic schema validators.

    This method orchestrates the complete deterministic validation
    pipeline by sequentially executing all registered validators
    and aggregating their warning outputs.

    Executed Validators:
        - Duplicate Index Validator
        - Foreign Key Index Validator
        - Timestamp Validator
        - Enum Modeling Validator
        - Composite Index Validator

    Args:
        schema:
            Structured schema response generated by the
            schema generation pipeline.

    Returns:
        list[DeterministicWarning]:
            Aggregated list of validation warnings generated
            across all validator modules.

    Used by:
        - generate_schema_service()

    Notes:
        - Validators are executed sequentially.
        - Validation pipeline is modular and easily extensible.
        - New validators can be integrated with minimal changes.
        - Validators are deterministic and rule-based.
        - Validation warnings are advisory unless enforced
          by downstream systems.
    """

    warnings = []

    # ============================================================
    # Duplicate Index Validation
    # ------------------------------------------------------------
    # Detect redundant unique index definitions.
    # ============================================================

    warnings.extend(
        validate_duplicate_indexes(schema)
    )

    # ============================================================
    # Foreign Key Index Validation
    # ------------------------------------------------------------
    # Ensure foreign key columns are properly indexed.
    # ============================================================

    warnings.extend(
        validate_foreign_key_indexes(schema)
    )

    # ============================================================
    # Timestamp Validation
    # ------------------------------------------------------------
    # Ensure standard audit timestamp fields exist.
    # ============================================================

    warnings.extend(
        validate_timestamps(schema)
    )

    # ============================================================
    # Enum Modeling Validation
    # ------------------------------------------------------------
    # Detect potential enum-style lookup table patterns.
    # ============================================================

    warnings.extend(
        validate_enum_modeling(schema)
    )

    # ============================================================
    # Composite Index Validation
    # ------------------------------------------------------------
    # Recommend composite indexes for query optimization.
    # ============================================================

    warnings.extend(
        validate_composite_indexes(schema)
    )

    # Return aggregated validation warnings
    return warnings