"""
Centralized validator execution pipeline responsible for orchestrating
all deterministic schema validation modules.

This module executes validators concurrently using worker threads
to improve scalability, fault isolation, and execution throughput.

The validator pipeline aggregates warnings generated from:
- duplicate index analysis
- foreign key index validation
- timestamp validation
- enum modeling analysis
- composite index recommendations

Architecture Features:
- concurrent validator execution
- isolated validator failures
- registry-based validator management
- centralized warning aggregation
- extensible validation framework

Used by:
- schema_service
- validation pipeline
- auto-fix engine
"""

import logging

from concurrent.futures import (
    ThreadPoolExecutor,
    as_completed
)

from models.schema_models import (
    SchemaResponse,
    DeterministicWarning
)

from utils.validators.duplicate_index_validator import (
    validate_duplicate_indexes
)

from utils.validators.foreign_key_validator import (
    validate_foreign_key_indexes
)

from utils.validators.timestamp_validator import (
    validate_timestamps
)

from utils.validators.enum_validator import (
    validate_enum_modeling
)

from utils.validators.composite_index_validator import (
    validate_composite_indexes
)


# ================================================================
# Configure module-level logger for validator execution tracing.
# ================================================================

logger = logging.getLogger(__name__)


# ================================================================
# Centralized validator registry.
# ---------------------------------------------------------------
# New validators can be added here without modifying the core
# execution pipeline.
# ================================================================

VALIDATORS = [
    validate_duplicate_indexes,
    validate_foreign_key_indexes,
    validate_timestamps,
    validate_enum_modeling,
    validate_composite_indexes,
]


def run_validators(
    schema: SchemaResponse
) -> list[DeterministicWarning]:
    """
    Execute all deterministic validators concurrently.

    This method orchestrates the complete validation pipeline
    using thread-based parallel execution.

    Each validator:
    - runs independently
    - operates in isolation
    - cannot break the overall pipeline on failure

    Executed Validators:
        - Duplicate Index Validator
        - Foreign Key Index Validator
        - Timestamp Validator
        - Enum Modeling Validator
        - Composite Index Validator

    Args:
        schema:
            Structured schema response generated by the
            schema generation pipeline.

    Returns:
        list[DeterministicWarning]:
            Aggregated validation warnings generated across
            all validators.

    Used by:
        - generate_schema_service()

    Notes:
        - Validators execute concurrently using worker threads.
        - Failures are isolated per validator.
        - Validation pipeline is modular and extensible.
        - ThreadPoolExecutor is suitable because validators are:
            - lightweight
            - stateless
            - read-only
            - I/O-light
    """

    warnings: list[DeterministicWarning] = []

    # ============================================================
    # Execute validators concurrently using worker threads.
    # ============================================================

    with ThreadPoolExecutor(
        max_workers=len(VALIDATORS)
    ) as executor:

        # ========================================================
        # Submit validators for parallel execution.
        # ========================================================

        future_map = {
            executor.submit(
                validator,
                schema
            ): validator.__name__
            for validator in VALIDATORS
        }

        # ========================================================
        # Process validator results as they complete.
        # ========================================================

        for future in as_completed(future_map):

            validator_name = future_map[future]

            try:

                result = future.result()

                if result:

                    warnings.extend(result)

                    logger.info(
                        f"[VALIDATOR_SUCCESS] "
                        f"{validator_name} generated "
                        f"{len(result)} warnings."
                    )

            # ====================================================
            # Isolate validator failures to prevent entire
            # validation pipeline from failing.
            # ====================================================

            except Exception as ex:

                logger.exception(
                    f"[VALIDATOR_FAILURE] "
                    f"{validator_name} failed: {str(ex)}"
                )

    # ============================================================
    # Return aggregated validation warnings.
    # ============================================================

    return warnings