"""
Schema validation utility responsible for enforcing deterministic
schema integrity and structural consistency rules.

This validator performs rule-based checks on generated schema output
before SQL compilation and deployment.

Current Validation Rules:
- prevents duplicate table names
- ensures PRIMARY KEY existence
- enforces created_at field presence
- enforces updated_at field presence

The validator acts as a safety layer between AI-generated schema
output and downstream compilation processes.

Used by:
- schema_service
- validation pipeline
- schema quality enforcement workflow
"""

from models.schema_models import SchemaResponse


def validate_schema(schema: SchemaResponse):
    """
    Validate generated schema against deterministic integrity rules.

    This method performs structural validation checks on all
    generated tables to ensure minimum schema quality standards.

    Validation Checks:
        - duplicate table name detection
        - PRIMARY KEY enforcement
        - created_at field enforcement
        - updated_at field enforcement

    Args:
        schema:
            Structured schema response generated by the
            schema generation pipeline.

    Returns:
        SchemaResponse:
            Validated schema object if all validation checks pass.

    Raises:
        ValueError:
            Raised when schema validation rules fail.

            Possible cases:
                - duplicate table names
                - missing PRIMARY KEY
                - missing created_at field
                - missing updated_at field

    Used by:
        - generate_schema_service()

    Notes:
        - Validation is deterministic and rule-based.
        - Designed to catch common schema quality issues
          before SQL compilation.
        - Validation logic can be extended with additional
          enterprise schema rules in future versions.
    """

    # Track processed table names to prevent duplicates
    table_names = set()

    for table in schema.tables:

        # ========================================================
        # Duplicate Table Name Validation
        # --------------------------------------------------------
        # Ensure all generated tables have unique names.
        # ========================================================

        if table.table_name in table_names:
            raise ValueError(
                f"Duplicate table name: {table.table_name}"
            )

        table_names.add(table.table_name)

        # ========================================================
        # PRIMARY KEY Validation
        # --------------------------------------------------------
        # Ensure each table contains a PRIMARY KEY definition.
        # ========================================================

        if "PRIMARY KEY" not in table.sql_query:
            raise ValueError(
                f"{table.table_name} missing PRIMARY KEY"
            )

        # ========================================================
        # created_at Field Validation
        # --------------------------------------------------------
        # Enforce audit timestamp support for record creation.
        # ========================================================

        if "created_at" not in table.sql_query:
            raise ValueError(
                f"{table.table_name} missing created_at"
            )

        # ========================================================
        # updated_at Field Validation
        # --------------------------------------------------------
        # Enforce audit timestamp support for record updates.
        # ========================================================

        if "updated_at" not in table.sql_query:
            raise ValueError(
                f"{table.table_name} missing updated_at"
            )

    # Return validated schema after successful checks
    return schema