"""
Schema generation agent responsible for producing normalized
database schema structures from analyzed application requirements.

This agent combines:
- extracted entities
- application features
- inferred relationships

to generate a complete structured database schema representation.

The generated schema is later consumed by:
- SQL Compiler
- Metadata Builder
- Architecture Review Agent

Flow:
1. Accept entities, features, and relationships
2. Inject contextual data into schema generation prompt
3. Invoke structured LLM schema generation
4. Return validated schema response
"""

from core.llm import llm
from prompts.generate_sql_prompt import generate_sql_query_prompt
from models.schema_models import SchemaResponse, RelationShip


# Configure structured schema generation output
structured_llm = llm.with_structured_output(SchemaResponse)


def generate_schema(
    entities: list[str],
    features: list[str],
    relationships: list[RelationShip]
):
    """
    Generate structured database schema from analyzed system metadata.

    This method produces a normalized schema definition by combining
    extracted entities, application features, and inferred relationships.

    Args:
        entities:
            List of extracted domain entities.

        features:
            List of identified application features/modules.

        relationships:
            List of inferred entity relationships generated by
            the relationship planning agent.

    Returns:
        dict:
            Structured database schema containing entities,
            attributes, constraints, and relationship mappings.

    Used by:
        - schema_service.generate_schema_service()

    Notes:
        - Output is validated against SchemaResponse schema.
        - Relationship context significantly impacts schema quality.
        - Generated schema acts as source input for SQL compilation.
    """

    prompt = generate_sql_query_prompt.format(
        entities=entities,
        features=features,
        relationships=relationships
    )

    response = structured_llm.invoke(prompt)

    return response.model_dump()