"""
Centralized Pydantic schema models used across the AI-driven
database schema generation platform.

This module defines all structured request/response contracts shared between:
- AI agents
- validation pipeline
- SQL compiler
- API layer
- metadata builder
- architecture review system

The models serve as:
- structured LLM output validators
- API contracts
- inter-service communication schemas
- deterministic validation containers

Design Goals:
- enforce strict response structure from LLMs
- improve downstream reliability
- standardize API responses
- simplify schema serialization/deserialization

Used by:
- Requirement Analysis Agent
- Relationship Planner Agent
- Schema Generator Agent
- Architecture Review Agent
- Validation Engine
- AutoFix Engine
- API Controllers
"""

from pydantic import BaseModel
from typing import List


class AutoFix(BaseModel):
    """
    Represents an automatically generated SQL fix for a detected issue.

    Used by:
        - AutoFix Engine
        - Deterministic Validators
        - Schema Repair Pipeline

    Attributes:
        issue:
            Description of the detected schema/design issue.

        fix_sql:
            SQL statement or correction generated to resolve the issue.
    """

    issue: str
    fix_sql: str


class AutoFixReport(BaseModel):
    """
    Container model for storing all generated schema auto-fixes.

    This model aggregates SQL correction suggestions generated
    during validation or architecture review phases.

    Used by:
        - AutoFix Engine
        - Validation Pipeline
        - API Response Serialization

    Attributes:
        fixes:
            List of generated SQL fixes and repair suggestions.
    """

    fixes: list[AutoFix]


class DeterministicWarning(BaseModel):
    """
    Represents a rule-based validation warning generated by
    deterministic validators.

    Unlike AI-generated warnings, deterministic warnings are
    produced through predefined validation logic and schema checks.

    Used by:
        - Validation Engine
        - Deterministic Rule Validators
        - API Response Layer

    Attributes:
        validator:
            Name of the validator that generated the warning.

        issue:
            Description of the detected schema issue.

        recommendation:
            Suggested resolution or improvement.
    """

    validator: str
    issue: str
    recommendation: str


class ValidationReport(BaseModel):
    """
    Aggregated validation report containing deterministic
    schema validation warnings.

    Used by:
        - Validation Pipeline
        - API Response Builder
        - Schema Review System

    Attributes:
        warnings:
            List of validation warnings generated during schema checks.
    """

    warnings: list[DeterministicWarning]


class MetaData(BaseModel):
    """
    Stores aggregated metadata about the generated schema output.

    Metadata is generated after schema compilation and is used
    for analytics, reporting, and quick schema summarization.

    Used by:
        - Metadata Builder
        - API Response Layer
        - Schema Analytics

    Attributes:
        total_tables:
            Total number of generated database tables.

        total_indexes:
            Total number of generated indexes across all tables.
    """

    total_tables: int
    total_indexes: int


class ExtraField(BaseModel):
    """
    Represents optional or AI-suggested additional database fields.

    These fields are not mandatory requirements but are recommended
    by the AI model to improve scalability, auditing, or usability.

    Examples:
        - created_at
        - updated_at
        - status
        - soft_delete flags

    Used by:
        - Schema Generator Agent
        - Architecture Review Pipeline

    Attributes:
        columnName:
            Suggested column name.

        reason:
            Justification for adding the field.
    """

    columnName: str
    reason: str


class ArchitectWarning(BaseModel):
    """
    Represents architecture-level schema design warnings
    generated during AI-driven review.

    Used by:
        - Architecture Review Agent
        - API Response Serialization

    Attributes:
        issue:
            Description of the architectural concern.

        recommendation:
            Suggested improvement or best practice recommendation.
    """

    issue: str
    recommendation: str


class ArchitectureReview(BaseModel):
    """
    Aggregated architecture review report generated by
    the Architecture Review Agent.

    Contains high-level schema design feedback and recommendations.

    Used by:
        - Architecture Review Agent
        - schema_service
        - API Response Layer

    Attributes:
        warnings:
            List of architecture-level review warnings.
    """

    warnings: list[ArchitectWarning]


class TableSchema(BaseModel):
    """
    Represents the schema definition for a single database table.

    Each table schema contains:
    - generated SQL query
    - index definitions
    - optional AI-suggested fields

    Used by:
        - Schema Generator Agent
        - SQL Compiler
        - Metadata Builder
        - API Response Serialization

    Attributes:
        table_name:
            Name of the generated database table.

        sql_query:
            SQL CREATE TABLE statement for the table.

        indexes:
            List of generated index definitions.

        extras:
            List of optional AI-suggested improvement fields.
    """

    table_name: str
    sql_query: str
    indexes: List[str]
    extras: List[ExtraField]


class SchemaResponse(BaseModel):
    """
    Primary API response model returned to clients after
    schema generation pipeline execution.

    This model aggregates:
    - generated schema
    - compiled SQL
    - metadata
    - validation warnings
    - architecture review feedback
    - auto-fix recommendations

    Used by:
        - API Controllers
        - schema_service
        - Frontend Clients

    Attributes:
        tables:
            Generated database table schemas.

        compiled_sql:
            Fully compiled SQL script combining all table queries.

        metadata:
            Aggregated schema metadata and statistics.

        architecture_review:
            AI-generated architecture review feedback.

        deterministic_warnings:
            Rule-based validation warnings.

        autofixes:
            Automatically generated SQL fixes.
    """

    tables: List[TableSchema]
    compiled_sql: str | None = None
    metadata: MetaData | None = None
    architecture_review: ArchitectureReview | None = None
    deterministic_warnings: list[DeterministicWarning] | None = None
    autofixes: list[AutoFix] | None = None


class SchemaRequest(BaseModel):
    """
    Primary API request model used for schema generation.

    This model accepts raw natural language application
    requirements from the user.

    Used by:
        - API Controllers
        - schema_service
        - Requirement Analysis Agent

    Attributes:
        user_input:
            Natural language system/application requirements.
    """

    user_input: str


class RequirementAnalysis(BaseModel):
    """
    Structured requirement analysis output generated by
    the Requirement Analysis Agent.

    This model acts as the foundational context layer
    for downstream AI agents.

    Used by:
        - Requirement Analysis Agent
        - Relationship Planner Agent
        - Schema Generator Agent

    Attributes:
        entities:
            Extracted business/domain entities.

        features:
            Extracted application features/modules.
    """

    entities: list[str]
    features: list[str]


class RelationShip(BaseModel):
    """
    Represents a database relationship between two entities.

    Used by:
        - Relationship Planner Agent
        - Schema Generator Agent
        - SQL Compiler

    Attributes:
        source:
            Source entity/table name.

        target:
            Target entity/table name.

        relationship_type:
            Relationship type definition.

            Examples:
                - one-to-one
                - one-to-many
                - many-to-many

        foreign_key:
            Foreign key field used for relationship mapping.
    """

    source: str
    target: str
    relationship_type: str
    foreign_key: str


class RelationShipPlan(BaseModel):
    """
    Aggregated relationship planning output generated
    by the Relationship Planner Agent.

    Used by:
        - Relationship Planner Agent
        - Schema Generator Agent
        - schema_service

    Attributes:
        relationships:
            List of inferred entity relationships.
    """

    relationships: list[RelationShip]